import { isColor } from '../../../src/utils/isColor'

describe('unit: isColor()', function () {
  it('should return true for valid color names', function () {
    // generated from: https://www.w3schools.com/colors/colors_names.asp using this script in console:
    // document.body.innerHTML = '<pre>' + Array.from(document.getElementsByClassName('colornamespan')).map((item) => "expect(isColor('" + item.innerText.toLowerCase() + "')).toBe(true)").join('\n') + '</pre>'

    // lowercase test
    expect(isColor('aliceblue')).toBe(true)
    expect(isColor('antiquewhite')).toBe(true)
    expect(isColor('aqua')).toBe(true)
    expect(isColor('aquamarine')).toBe(true)
    expect(isColor('azure')).toBe(true)
    expect(isColor('beige')).toBe(true)
    expect(isColor('bisque')).toBe(true)
    expect(isColor('black')).toBe(true)
    expect(isColor('blanchedalmond')).toBe(true)
    expect(isColor('blue')).toBe(true)
    expect(isColor('blueviolet')).toBe(true)
    expect(isColor('brown')).toBe(true)
    expect(isColor('burlywood')).toBe(true)
    expect(isColor('cadetblue')).toBe(true)
    expect(isColor('chartreuse')).toBe(true)
    expect(isColor('chocolate')).toBe(true)
    expect(isColor('coral')).toBe(true)
    expect(isColor('cornflowerblue')).toBe(true)
    expect(isColor('cornsilk')).toBe(true)
    expect(isColor('crimson')).toBe(true)
    expect(isColor('cyan')).toBe(true)
    expect(isColor('darkblue')).toBe(true)
    expect(isColor('darkcyan')).toBe(true)
    expect(isColor('darkgoldenrod')).toBe(true)
    expect(isColor('darkgray')).toBe(true)
    expect(isColor('darkgrey')).toBe(true)
    expect(isColor('darkgreen')).toBe(true)
    expect(isColor('darkkhaki')).toBe(true)
    expect(isColor('darkmagenta')).toBe(true)
    expect(isColor('darkolivegreen')).toBe(true)
    expect(isColor('darkorange')).toBe(true)
    expect(isColor('darkorchid')).toBe(true)
    expect(isColor('darkred')).toBe(true)
    expect(isColor('darksalmon')).toBe(true)
    expect(isColor('darkseagreen')).toBe(true)
    expect(isColor('darkslateblue')).toBe(true)
    expect(isColor('darkslategray')).toBe(true)
    expect(isColor('darkslategrey')).toBe(true)
    expect(isColor('darkturquoise')).toBe(true)
    expect(isColor('darkviolet')).toBe(true)
    expect(isColor('deeppink')).toBe(true)
    expect(isColor('deepskyblue')).toBe(true)
    expect(isColor('dimgray')).toBe(true)
    expect(isColor('dimgrey')).toBe(true)
    expect(isColor('dodgerblue')).toBe(true)
    expect(isColor('firebrick')).toBe(true)
    expect(isColor('floralwhite')).toBe(true)
    expect(isColor('forestgreen')).toBe(true)
    expect(isColor('fuchsia')).toBe(true)
    expect(isColor('gainsboro')).toBe(true)
    expect(isColor('ghostwhite')).toBe(true)
    expect(isColor('gold')).toBe(true)
    expect(isColor('goldenrod')).toBe(true)
    expect(isColor('gray')).toBe(true)
    expect(isColor('grey')).toBe(true)
    expect(isColor('green')).toBe(true)
    expect(isColor('greenyellow')).toBe(true)
    expect(isColor('honeydew')).toBe(true)
    expect(isColor('hotpink')).toBe(true)
    expect(isColor('indianred')).toBe(true)
    expect(isColor('indigo')).toBe(true)
    expect(isColor('ivory')).toBe(true)
    expect(isColor('khaki')).toBe(true)
    expect(isColor('lavender')).toBe(true)
    expect(isColor('lavenderblush')).toBe(true)
    expect(isColor('lawngreen')).toBe(true)
    expect(isColor('lemonchiffon')).toBe(true)
    expect(isColor('lightblue')).toBe(true)
    expect(isColor('lightcoral')).toBe(true)
    expect(isColor('lightcyan')).toBe(true)
    expect(isColor('lightgoldenrodyellow')).toBe(true)
    expect(isColor('lightgray')).toBe(true)
    expect(isColor('lightgrey')).toBe(true)
    expect(isColor('lightgreen')).toBe(true)
    expect(isColor('lightpink')).toBe(true)
    expect(isColor('lightsalmon')).toBe(true)
    expect(isColor('lightseagreen')).toBe(true)
    expect(isColor('lightskyblue')).toBe(true)
    expect(isColor('lightslategray')).toBe(true)
    expect(isColor('lightslategrey')).toBe(true)
    expect(isColor('lightsteelblue')).toBe(true)
    expect(isColor('lightyellow')).toBe(true)
    expect(isColor('lime')).toBe(true)
    expect(isColor('limegreen')).toBe(true)
    expect(isColor('linen')).toBe(true)
    expect(isColor('magenta')).toBe(true)
    expect(isColor('maroon')).toBe(true)
    expect(isColor('mediumaquamarine')).toBe(true)
    expect(isColor('mediumblue')).toBe(true)
    expect(isColor('mediumorchid')).toBe(true)
    expect(isColor('mediumpurple')).toBe(true)
    expect(isColor('mediumseagreen')).toBe(true)
    expect(isColor('mediumslateblue')).toBe(true)
    expect(isColor('mediumspringgreen')).toBe(true)
    expect(isColor('mediumturquoise')).toBe(true)
    expect(isColor('mediumvioletred')).toBe(true)
    expect(isColor('midnightblue')).toBe(true)
    expect(isColor('mintcream')).toBe(true)
    expect(isColor('mistyrose')).toBe(true)
    expect(isColor('moccasin')).toBe(true)
    expect(isColor('navajowhite')).toBe(true)
    expect(isColor('navy')).toBe(true)
    expect(isColor('oldlace')).toBe(true)
    expect(isColor('olive')).toBe(true)
    expect(isColor('olivedrab')).toBe(true)
    expect(isColor('orange')).toBe(true)
    expect(isColor('orangered')).toBe(true)
    expect(isColor('orchid')).toBe(true)
    expect(isColor('palegoldenrod')).toBe(true)
    expect(isColor('palegreen')).toBe(true)
    expect(isColor('paleturquoise')).toBe(true)
    expect(isColor('palevioletred')).toBe(true)
    expect(isColor('papayawhip')).toBe(true)
    expect(isColor('peachpuff')).toBe(true)
    expect(isColor('peru')).toBe(true)
    expect(isColor('pink')).toBe(true)
    expect(isColor('plum')).toBe(true)
    expect(isColor('powderblue')).toBe(true)
    expect(isColor('purple')).toBe(true)
    expect(isColor('rebeccapurple')).toBe(true)
    expect(isColor('red')).toBe(true)
    expect(isColor('rosybrown')).toBe(true)
    expect(isColor('royalblue')).toBe(true)
    expect(isColor('saddlebrown')).toBe(true)
    expect(isColor('salmon')).toBe(true)
    expect(isColor('sandybrown')).toBe(true)
    expect(isColor('seagreen')).toBe(true)
    expect(isColor('seashell')).toBe(true)
    expect(isColor('sienna')).toBe(true)
    expect(isColor('silver')).toBe(true)
    expect(isColor('skyblue')).toBe(true)
    expect(isColor('slateblue')).toBe(true)
    expect(isColor('slategray')).toBe(true)
    expect(isColor('slategrey')).toBe(true)
    expect(isColor('snow')).toBe(true)
    expect(isColor('springgreen')).toBe(true)
    expect(isColor('steelblue')).toBe(true)
    expect(isColor('tan')).toBe(true)
    expect(isColor('teal')).toBe(true)
    expect(isColor('thistle')).toBe(true)
    expect(isColor('tomato')).toBe(true)
    expect(isColor('turquoise')).toBe(true)
    expect(isColor('violet')).toBe(true)
    expect(isColor('wheat')).toBe(true)
    expect(isColor('white')).toBe(true)
    expect(isColor('whitesmoke')).toBe(true)
    expect(isColor('yellow')).toBe(true)
    expect(isColor('yellowgreen')).toBe(true)

    // uppercase test
    expect(isColor('AliceBlue')).toBe(true)
    expect(isColor('AntiqueWhite')).toBe(true)
    expect(isColor('Aqua')).toBe(true)
    expect(isColor('Aquamarine')).toBe(true)
    expect(isColor('Azure')).toBe(true)
    expect(isColor('Beige')).toBe(true)
    expect(isColor('Bisque')).toBe(true)
    expect(isColor('Black')).toBe(true)
    expect(isColor('BlanchedAlmond')).toBe(true)
    expect(isColor('Blue')).toBe(true)
    expect(isColor('BlueViolet')).toBe(true)
    expect(isColor('Brown')).toBe(true)
    expect(isColor('BurlyWood')).toBe(true)
    expect(isColor('CadetBlue')).toBe(true)
    expect(isColor('Chartreuse')).toBe(true)
    expect(isColor('Chocolate')).toBe(true)
    expect(isColor('Coral')).toBe(true)
    expect(isColor('CornflowerBlue')).toBe(true)
    expect(isColor('Cornsilk')).toBe(true)
    expect(isColor('Crimson')).toBe(true)
    expect(isColor('Cyan')).toBe(true)
    expect(isColor('DarkBlue')).toBe(true)
    expect(isColor('DarkCyan')).toBe(true)
    expect(isColor('DarkGoldenRod')).toBe(true)
    expect(isColor('DarkGray')).toBe(true)
    expect(isColor('DarkGrey')).toBe(true)
    expect(isColor('DarkGreen')).toBe(true)
    expect(isColor('DarkKhaki')).toBe(true)
    expect(isColor('DarkMagenta')).toBe(true)
    expect(isColor('DarkOliveGreen')).toBe(true)
    expect(isColor('DarkOrange')).toBe(true)
    expect(isColor('DarkOrchid')).toBe(true)
    expect(isColor('DarkRed')).toBe(true)
    expect(isColor('DarkSalmon')).toBe(true)
    expect(isColor('DarkSeaGreen')).toBe(true)
    expect(isColor('DarkSlateBlue')).toBe(true)
    expect(isColor('DarkSlateGray')).toBe(true)
    expect(isColor('DarkSlateGrey')).toBe(true)
    expect(isColor('DarkTurquoise')).toBe(true)
    expect(isColor('DarkViolet')).toBe(true)
    expect(isColor('DeepPink')).toBe(true)
    expect(isColor('DeepSkyBlue')).toBe(true)
    expect(isColor('DimGray')).toBe(true)
    expect(isColor('DimGrey')).toBe(true)
    expect(isColor('DodgerBlue')).toBe(true)
    expect(isColor('FireBrick')).toBe(true)
    expect(isColor('FloralWhite')).toBe(true)
    expect(isColor('ForestGreen')).toBe(true)
    expect(isColor('Fuchsia')).toBe(true)
    expect(isColor('Gainsboro')).toBe(true)
    expect(isColor('GhostWhite')).toBe(true)
    expect(isColor('Gold')).toBe(true)
    expect(isColor('GoldenRod')).toBe(true)
    expect(isColor('Gray')).toBe(true)
    expect(isColor('Grey')).toBe(true)
    expect(isColor('Green')).toBe(true)
    expect(isColor('GreenYellow')).toBe(true)
    expect(isColor('HoneyDew')).toBe(true)
    expect(isColor('HotPink')).toBe(true)
    expect(isColor('IndianRed')).toBe(true)
    expect(isColor('Indigo')).toBe(true)
    expect(isColor('Ivory')).toBe(true)
    expect(isColor('Khaki')).toBe(true)
    expect(isColor('Lavender')).toBe(true)
    expect(isColor('LavenderBlush')).toBe(true)
    expect(isColor('LawnGreen')).toBe(true)
    expect(isColor('LemonChiffon')).toBe(true)
    expect(isColor('LightBlue')).toBe(true)
    expect(isColor('LightCoral')).toBe(true)
    expect(isColor('LightCyan')).toBe(true)
    expect(isColor('LightGoldenRodYellow')).toBe(true)
    expect(isColor('LightGray')).toBe(true)
    expect(isColor('LightGrey')).toBe(true)
    expect(isColor('LightGreen')).toBe(true)
    expect(isColor('LightPink')).toBe(true)
    expect(isColor('LightSalmon')).toBe(true)
    expect(isColor('LightSeaGreen')).toBe(true)
    expect(isColor('LightSkyBlue')).toBe(true)
    expect(isColor('LightSlateGray')).toBe(true)
    expect(isColor('LightSlateGrey')).toBe(true)
    expect(isColor('LightSteelBlue')).toBe(true)
    expect(isColor('LightYellow')).toBe(true)
    expect(isColor('Lime')).toBe(true)
    expect(isColor('LimeGreen')).toBe(true)
    expect(isColor('Linen')).toBe(true)
    expect(isColor('Magenta')).toBe(true)
    expect(isColor('Maroon')).toBe(true)
    expect(isColor('MediumAquaMarine')).toBe(true)
    expect(isColor('MediumBlue')).toBe(true)
    expect(isColor('MediumOrchid')).toBe(true)
    expect(isColor('MediumPurple')).toBe(true)
    expect(isColor('MediumSeaGreen')).toBe(true)
    expect(isColor('MediumSlateBlue')).toBe(true)
    expect(isColor('MediumSpringGreen')).toBe(true)
    expect(isColor('MediumTurquoise')).toBe(true)
    expect(isColor('MediumVioletRed')).toBe(true)
    expect(isColor('MidnightBlue')).toBe(true)
    expect(isColor('MintCream')).toBe(true)
    expect(isColor('MistyRose')).toBe(true)
    expect(isColor('Moccasin')).toBe(true)
    expect(isColor('NavajoWhite')).toBe(true)
    expect(isColor('Navy')).toBe(true)
    expect(isColor('OldLace')).toBe(true)
    expect(isColor('Olive')).toBe(true)
    expect(isColor('OliveDrab')).toBe(true)
    expect(isColor('Orange')).toBe(true)
    expect(isColor('OrangeRed')).toBe(true)
    expect(isColor('Orchid')).toBe(true)
    expect(isColor('PaleGoldenRod')).toBe(true)
    expect(isColor('PaleGreen')).toBe(true)
    expect(isColor('PaleTurquoise')).toBe(true)
    expect(isColor('PaleVioletRed')).toBe(true)
    expect(isColor('PapayaWhip')).toBe(true)
    expect(isColor('PeachPuff')).toBe(true)
    expect(isColor('Peru')).toBe(true)
    expect(isColor('Pink')).toBe(true)
    expect(isColor('Plum')).toBe(true)
    expect(isColor('PowderBlue')).toBe(true)
    expect(isColor('Purple')).toBe(true)
    expect(isColor('RebeccaPurple')).toBe(true)
    expect(isColor('Red')).toBe(true)
    expect(isColor('RosyBrown')).toBe(true)
    expect(isColor('RoyalBlue')).toBe(true)
    expect(isColor('SaddleBrown')).toBe(true)
    expect(isColor('Salmon')).toBe(true)
    expect(isColor('SandyBrown')).toBe(true)
    expect(isColor('SeaGreen')).toBe(true)
    expect(isColor('SeaShell')).toBe(true)
    expect(isColor('Sienna')).toBe(true)
    expect(isColor('Silver')).toBe(true)
    expect(isColor('SkyBlue')).toBe(true)
    expect(isColor('SlateBlue')).toBe(true)
    expect(isColor('SlateGray')).toBe(true)
    expect(isColor('SlateGrey')).toBe(true)
    expect(isColor('Snow')).toBe(true)
    expect(isColor('SpringGreen')).toBe(true)
    expect(isColor('SteelBlue')).toBe(true)
    expect(isColor('Tan')).toBe(true)
    expect(isColor('Teal')).toBe(true)
    expect(isColor('Thistle')).toBe(true)
    expect(isColor('Tomato')).toBe(true)
    expect(isColor('Turquoise')).toBe(true)
    expect(isColor('Violet')).toBe(true)
    expect(isColor('Wheat')).toBe(true)
    expect(isColor('White')).toBe(true)
    expect(isColor('WhiteSmoke')).toBe(true)
    expect(isColor('Yellow')).toBe(true)
    expect(isColor('YellowGreen')).toBe(true)
  })

  it('should return true for valid hex color values', function () {
    expect(isColor('#f09')).toBe(true)
    expect(isColor('#F09')).toBe(true)
    expect(isColor('#ff0099')).toBe(true)
    expect(isColor('#FF0099')).toBe(true)

    // with transparency
    expect(isColor('#3a30')).toBe(true)
    expect(isColor('#3A3F')).toBe(true)
    expect(isColor('#33aa3300')).toBe(true)
    expect(isColor('#33AA3380')).toBe(true)
    expect(isColor('#f09f')).toBe(true)
    expect(isColor('#F09F')).toBe(true)
    expect(isColor('#ff0099ff')).toBe(true)
    expect(isColor('#FF0099FF')).toBe(true)
  })

  it('should return true for valid rgb() function colors', function () {
    expect(isColor('rgb(255,0,153)')).toBe(true)
    expect(isColor('rgb(255, 0, 153)')).toBe(true)
    // expect(isColor('rgb(255, 0, 153.0)')).toBe(true) <-- TODO: fix me
    expect(isColor('rgb(100%,0%,60%)')).toBe(true)
    expect(isColor('rgb(100%, 0%, 60%)')).toBe(true)

    // whitespace syntax
    // TODO: fix whitespace syntax
    // expect(isColor('rgb(51 170 51')).toBe(true)
    // expect(isColor('rgb(51 170 51')).toBe(true)

    // with float values
    // TODO: fix float values
    // expect(isColor('rgb(255, 0, 153.6)')).toBe(true)
    // expect(isColor('rgb(2.55e2, 0e0, 1.53e2)')).toBe(true)
  })

  it('should return true for valid rgba() function colors', function () {
    expect(isColor('rgba(51, 170, 51, .1)')).toBe(true)
    expect(isColor('rgba(51, 170, 51, .4)')).toBe(true)
    expect(isColor('rgba(51, 170, 51, .7)')).toBe(true)
    expect(isColor('rgba(51, 170, 51,  1)')).toBe(true)

    // whitespace syntax
    // TODO: fix whitespace syntax
    // expect(isColor('rgba(51 170 51 / 0.4')).toBe(true)
    // expect(isColor('rgba(51 170 51 / 40%')).toBe(true)

    // with float values
    // TODO: fix float values
    // expect(isColor('rgba(255, 0, 153.6, 1)')).toBe(true)
    // expect(isColor('rgba(2.55e2, 0e0, 1.53e2, 1e2%)')).toBe(true)
  })

  it('should return true for valid hsl() function colors', function () {
    expect(isColor('hsl(270,60%,70%)')).toBe(true)
    expect(isColor('hsl(270, 60%, 70%)')).toBe(true)

    // TODO: fix hsl syntax values
    // expect(isColor('hsl(270 60% 70%)')).toBe(true)
    // expect(isColor('hsl(270deg, 60%, 70%)')).toBe(true)
    // expect(isColor('hsl(4.71239rad, 60%, 70%)')).toBe(true)
    // expect(isColor('hsl(.75turn, 60%, 70%)')).toBe(true)
  })

  it('should return true for valid hsla() function colors', function () {
    expect(isColor('hsla(270, 60%, 50%, .15)')).toBe(true)
    expect(isColor('hsla(240, 100%, 50%, .05)')).toBe(true)
    expect(isColor('hsla(240, 100%, 50%, .4)')).toBe(true)
    expect(isColor('hsla(240, 100%, 50%, .7)')).toBe(true)
    expect(isColor('hsla(240, 100%, 50%, 1)')).toBe(true)

    // TODO: fix hsla syntax values
    // expect(isColor('hsla(270, 60%, 50%, 15%)')).toBe(true)
    // expect(isColor('hsla(270 60% 50% / .15)')).toBe(true)
    // expect(isColor('hsla(270 60% 50% / 15%)')).toBe(true)
  })

  it('should return false for invalid color values', function () {
    expect(isColor('invalid-color')).toBe(false)
    expect(isColor('reds')).toBe(false)
    expect(isColor('#YYYYY')).toBe(false)
    expect(isColor('rgb(test, 2, testing)')).toBe(false)
    expect(isColor('rgba(test, 2, testing, 0.1)')).toBe(false)
    expect(isColor('hsl(test, 2, testing)')).toBe(false)
    expect(isColor('hsla(test, 2, testing, 1)')).toBe(false)
  })
})
